### ISSUE TITLE
Понятие алгоритма

### ISSUE THREAD

**Issue by ILScc** [HowProgrammingWorks/Book#120]
В главе [1-4](https://github.com/HowProgrammingWorks/Book/blob/master/content/ru/1-4-Program.md) вводится однозначное определение алгоритма, что некорректно с точки зрения существования теории вычислимости. Более того, введенное здесь понятие алгоритма применимо только к императивному программированию, что понятно по наличию в определении слова "порядок вычислений" (в, например, функциональном программировании ни о каком порядке вычислений речи идти не может)
Подтверждение можно найти, например, в книгах А.В. Столярова - [Том 1. Азы программирования ](http://www.stolyarov.info/books/programming_intro/e2) (конкретную часть текста приложить не могу в связи с лицензией книги). 

Предлагаю либо убрать это пояснение об алгоритме вовсе, либо изменить формулировку на не такую строгую (добавить "может являться" в начало предложения), либо изменить его совершенно на, например, `алгоритм - некая конструктивная реализация преобразования входных значений в выходные` , но такое определение не совсем корректно (отсутствует пояснение про принадлежность входного и выходного слова к некоему алфавиту) и требует дополнительных пояснений, хотя бы почему же все таки здесь не использовано определение из классического учебника информатики  
![image](https://user-images.githubusercontent.com/74474615/177050702-e12d18b2-ee82-4c58-9d10-609163cbf6d0.png)

**Comment by AntiHero** [comment]
К слову, существующее определние, на мой взгяд, похоже частично на то, что дал в своей книге Кнут, поэтому может имеет смысл просто добавить ссылки на источники, где читатель может посмотерть более подробное определение алгоритма или на различные авторские варианты определений

**Comment by tshemsedinov** [comment]
@ILScc Функциональная парадигма задает задает порядок вычислений, но в части случаев он может быть исполнен параллельно или последовательно, но в разном порядке, грубо говоря, скобки есть скобками, а порядок сложения чисел не важен.

Со Столяровым я частично могу согласиться, и вся книга переработана в том ключе, что теперь нет формальных определений, а для каждого понятия выделен целый абзац, где оно освещается с разных сторон, понятными словами, а не чеканными терминами. Ваше определение совершенно не добавит понимания начинающему. Смотрите, как я переписал в книге.
