### ISSUE TITLE
Render lists to PDF

### ISSUE THREAD

**Issue by tshemsedinov** [HowProgrammingWorks/Book#129]
Try to render it like github do that. Here is an example in this chapter: https://github.com/HowProgrammingWorks/Book/blob/master/content/ru/2-1-Identifiers.md

**Comment by Eternal-Rise** [comment]
I can do it

**Comment by tshemsedinov** [comment]
That's ok to support just `-` buller and convert to `ul/li` tags @Eternal-Rise

**Comment by tshemsedinov** [comment]
Done: https://github.com/HowProgrammingWorks/Book/pull/135
