### ISSUE TITLE
Rename book

### ISSUE THREAD

**Issue by tshemsedinov** [HowProgrammingWorks/Book#34]
Current: Multi-paradigm and Meta-programming in the Software Engineering

Proposed:
- Metaprogramming
- Multi-paradigm programming
- Metaprogramming and Multi-paradigm programming

Add subtitle:
- approach in the Software Engineering, etc.

**Comment by gsvcrypto** [comment]
I like the last item:
Meta-programming and Multi-paradigm programming approach in the Software Engineering

**Comment by tursky** [comment]
Title: Essence of Metaprogramming 
Subtitle: Multi-paradigm approach in the Software Engineering

**Comment by tursky** [comment]
I have several opinions.

1. The title should contain several words, one of which is "Metaprogramming"
   with a capital letter, which would emphasize the Metarhia brand. A little
   visualization doesn't hurt.

![Screenshot from 2022-01-27 20-26-59](https://user-images.githubusercontent.com/44061259/151427710-8ef6580f-e7b7-4b8f-8c6d-abdb17d51b58.png)

[ "Basics of Metaprogramming", "Fundamentals of Metaprogramming", "Prism of Metaprogramming", "Learning Metaprogramming", "Metaprogramming research", "Implementing Metaprogramming"  ]

In this case, the subtitle is not required, actually.

2. I studied the table of contents and found that the book has a very wide range
   of topics, but the word "metaprogramming" occurs there only 1 time. There's
   more about paradigms, basics, etc. I believe the topic of
   metaprogramming will be presented through the synthesis of multi-paradigm
   programming and much more. In this case, we can swap the title and subtitle.

![Screenshot from 2022-01-27 20-28-34](https://user-images.githubusercontent.com/44061259/151427869-68ec253a-bc45-4f78-84c0-c36267f9f707.png)

The long title sounds suggestive and scientific (more specifically). But the short name is more memorable. In both cases, the second part of the title should be in small print.

I don't think I said anything new. I like both options anyway.

**Comment by tursky** [comment]
Third option:
- Introduction to Metaprogramming
- The essence of the multi-paradigm approach 

This name will be attractive to both beginners and professionals.

![Screenshot from 2022-01-28 12-19-07](https://user-images.githubusercontent.com/44061259/151530658-5fab1cca-81e1-408f-92e2-a703688a34a8.png)
