### ISSUE TITLE
Links to book's index are broken

### ISSUE THREAD

**Issue by timagixe** [HowProgrammingWorks/Book#79]
**Describe the bug**
Both links in the repository's [README.md](https://github.com/HowProgrammingWorks/Book/blob/master/README.md) file that should navigate user to a book's index are broken.

**Expected alternatives**
Update links to a valid one from (i.e. for English [Book/content/en/Index.md](https://github.com/HowProgrammingWorks/Book/blob/master/content/en/Index.md))

**Screenshots**
N/A

**Add references**
N/A

**Comment by tshemsedinov** [comment]
@timagixe Thanks!
